#!/bin/bash
# Combined Cloudflare Workers (free) + AI Gateway (paid, <$20)

CONFIG=".blob/extensions/model/budget-config.json"

echo "Model Strategy: Cloudflare Workers + AI Gateway"
echo ""
echo "Budget: $20/month"
echo ""
echo "1. Cloudflare Workers AI (FREE)"
echo "   - 10,000 neurons/day"
echo "   - Qwen3 30B: ~60-70 requests/day"
echo "   - Use this FIRST always"
echo ""
echo "2. AI Gateway (paid, only if needed)"
echo "   - DeepSeek: $0.50/1M (cheap backup)"
echo "   - GPT-4.1-mini: $2/1M (reliable)"
echo "   - Claude: $9/1M (expensive, rare)"
echo ""
echo "Strategy:"
echo "  ✓ Use Cloudflare Workers for everything possible"
echo "  ✓ Fallback to AI Gateway only when Workers fails"
echo "  ✓ Prefer DeepSeek or GPT-4.1-mini (cheaper)"
echo "  ✓ Claude only for complex architecture"
echo ""
echo "With 10k free neurons + $20, you get:"
echo "  - Unlimited simple tasks (Cloudflare)"
echo "  - ~10M tokens on DeepSeek, or"
echo "  - ~2M tokens on GPT-4.1-mini, or"
echo "  - Mix of all"
