#!/bin/bash
# Cloudflare Workers AI - Best models for agents

echo "Cloudflare Workers AI"
echo ""
echo "Free: 10,000 neurons/day"
echo ""
echo "Recommended models for Blob:"
echo ""
echo "agent (DEFAULT)"
echo "  @cf/qwen/qwen3-30b-a3b-fp8"
echo "  ~120 neurons - Best agent/tool capabilities"
echo ""
echo "fast"
echo "  @cf/zai-org/glm-4.7-flash"
echo "  ~50 neurons - Quick responses"
echo ""
echo "powerful"
echo "  @cf/meta/llama-3.3-70b-instruct-fp8-fast"
echo "  ~150 neurons - Hardest problems"
echo ""
echo "Tip: Qwen3 30B is best for coding agents with tool use!"
