import { TOOL_OUTPUT_MAX_CHARS } from "./config";
import type { ToolResult } from "./types";

export interface DynamicToolDefinition {
  name: string;
  description: string;
  commandTemplate: string;
  args: string[];
}

export const BASH_TOOL = {
  name: "bash",
  description: "Execute a bash command inside the configured sandbox.",
  input_schema: {
    type: "object",
    properties: {
      command: {
        type: "string",
        description: "Shell command to execute"
      }
    },
    required: ["command"]
  }
} as const;

export const CREATE_TOOL_TOOL = {
  name: "create_tool",
  description: "Create a reusable command tool. Use this when the same shell workflow will be run repeatedly.",
  input_schema: {
    type: "object",
    properties: {
      name: { type: "string", description: "Tool name in snake_case, e.g. list_repo_files" },
      description: { type: "string", description: "What the tool does and when to use it" },
      command_template: { type: "string", description: "Bash command template. Use {arg_name} placeholders for arguments." },
      args: {
        type: "array",
        description: "Argument names used by command_template placeholders",
        items: { type: "string" }
      }
    },
    required: ["name", "description", "command_template"],
    additionalProperties: false
  }
} as const;

export const WEB_FETCH_TOOL = {
  name: "web_fetch",
  description: "Fetch a web page and return its content as markdown. Use this to read web pages. Returns only text content, no scripts or styles.",
  input_schema: {
    type: "object",
    properties: {
      url: {
        type: "string",
        description: "URL to fetch (must be http or https)"
      },
      max_length: {
        type: "number",
        description: "Maximum characters to return (default 4000)"
      }
    },
    required: ["url"]
  }
} as const;

export function sanitizeToolName(rawName: string): string {
  return rawName.trim().toLowerCase().replace(/[^a-z0-9_]/g, "_");
}

export function validateDynamicToolDefinition(input: Record<string, unknown>): { ok: true; definition: DynamicToolDefinition } | { ok: false; reason: string } {
  const rawName = String(input.name ?? "").trim();
  const description = String(input.description ?? "").trim();
  const commandTemplate = String(input.command_template ?? "").trim();
  const providedArgs = Array.isArray(input.args) ? input.args.map((arg) => String(arg).trim()).filter(Boolean) : [];

  if (!rawName || !description || !commandTemplate) {
    return { ok: false, reason: "name, description, and command_template are required." };
  }

  const name = sanitizeToolName(rawName);
  if (!/^[a-z][a-z0-9_]{1,63}$/.test(name)) {
    return { ok: false, reason: "Tool name must start with a letter and contain only lowercase letters, numbers, or underscores (2-64 chars)." };
  }

  if (name === "bash" || name === "create_tool") {
    return { ok: false, reason: `Tool name \"${name}\" is reserved.` };
  }

  const placeholderArgs = Array.from(commandTemplate.matchAll(/\{([a-zA-Z_][a-zA-Z0-9_]*)\}/g)).map((match) => match[1]);
  const args = Array.from(new Set([...providedArgs, ...placeholderArgs]));

  return {
    ok: true,
    definition: {
      name,
      description,
      commandTemplate,
      args
    }
  };
}

export function dynamicToolToAnthropicSchema(tool: DynamicToolDefinition) {
  const properties = Object.fromEntries(tool.args.map((arg) => [arg, { type: "string", description: `${arg} value` }]));

  return {
    name: tool.name,
    description: `${tool.description} (Generated by Blob during this session)`,
    input_schema: {
      type: "object",
      properties,
      required: tool.args,
      additionalProperties: false
    }
  };
}

export function compileDynamicToolCommand(tool: DynamicToolDefinition, input: Record<string, unknown>): { ok: true; command: string } | { ok: false; reason: string } {
  let command = tool.commandTemplate;
  for (const arg of tool.args) {
    const value = input[arg];
    if (value === undefined || value === null) {
      return { ok: false, reason: `Missing required argument: ${arg}` };
    }
    command = command.replaceAll(`{${arg}}`, String(value));
  }

  return { ok: true, command };
}

export function formatToolResult(toolUseId: string, output: string, maxChars = TOOL_OUTPUT_MAX_CHARS): ToolResult {
  const trimmed = output.length > maxChars
    ? `${output.slice(0, maxChars)}\n\n[output truncated: ${output.length - maxChars} characters omitted]`
    : output;

  return {
    type: "tool_result",
    tool_use_id: toolUseId,
    content: [{ type: "text", text: trimmed }]
  };
}
